### ISSUE TITLE
your web -demo do'nt change

### ISSUE THREAD

**Issue by liuliucai** [imadelh/ML-web-app#3]
why do your web -demo  no change!

![err](https://user-images.githubusercontent.com/51130345/75742664-492e7a80-5d49-11ea-9078-efe141d6cd9d.png)

**Comment by imadelh** [comment]
@liuliucai you have to activate javascript in your browser.

**Comment by liuliucai** [comment]
clone the demo .no change code.
run app
RuntimeError: Given input size: (64x28x1). Calculated output size: (64x14x0). Output size is too small

**Comment by Torrakanor611** [comment]
did you manage to fix this error above @liuliucai @imadelh, if soo how?
thx in advance
